config/routes.rb
Rails.application.routes.draw do
  resources :labels


  resources :tasks
  resources :users
  resources :sessions

  namespace :admin do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user
  has_many :labels

  enum status: { non_progress: 1, in_progress: 2, complete: 3, pending: 4 }
  validates :title, presence: true
  validates :text, presence: true

  scope :search, ->(word) { where('tasks.title like ?', '%' + word.gsub(/[\\%_]/) { |m| "\\#{m}" } + '%') }

  scope :search, lambda { |freeword|
    where(
      'tasks.title like :freeword or tasks.text like :freeword',
      freeword: '%' + freeword.gsub(/[\\%_]/) { |m| "\\#{m}" } + '%'
    )
  }

end

app/models/user.rb
class User < ApplicationRecord

  has_many :tasks
  has_many :labels
  enum user_type: { admin: 1, normal: 2 }
  scope :admin, -> { where(user_type: User.user_types[:admin]) }

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  layout "admin"
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.page(params[:page]).per(3)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(users_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def update
    @user.update(users_params)
    redirect_to admin_users_path
  end

  def destroy
    @user.tasks.destroy_all
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def users_params
    params.require(:user).permit(:name, :password, :email, :user_type)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin_check

  def admin_check
    unless current_user
      return redirect_to tasks_path
    end

    unless current_user.admin?
      redirect_to tasks_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def judge_login
    if session[:user_id].nil?
      redirect_to new_session_path
    end
  end

  def login_user_reject
    if session[:user_id]
      redirect_to tasks_path
    end
  end

  def current_user
    if session[:user_id]
      if User.find(session[:user_id])
        currenrt_user = User.find(session[:user_id])
      end
    end
  end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :judge_login
  before_action :set_label, only: [:edit, :update, :destroy]
  before_action :set_labels, only: [:edit, :new]


  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
    @task_id = params[:task_id]
  end

  # GET /labels/1/edit
  def edit
    @task_id = params[:task_id]
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    if @label.update(label_params)
      redirect_to tasks_path
    else
      render :edit
    end

  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    redirect_to tasks_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    def set_labels
      @labels = current_user.labels
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name, :user_id, :task_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :judge_login, only: :destroy
  before_action :login_user_reject, only: [:new, :create]

  def new
  end

  def create
    user = User.where(email: params[:email]).last
    @user = user
    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to tasks_path
    else
      render :new
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :judge_login
  before_action :set_task, only: [:edit, :update, :destroy]
  def index
    search
    @tasks = @tasks.page(params[:page]).per(3)
    @labels = current_user.labels

  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(tasks_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def update
    @task.update(tasks_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:title, :text, :status, :deadline, :priority, :user_id)
  end

  def search
    status = params[:status]
    word = params[:word]
    label = params[:label]
    sorted_by = params[:sorted_by]

    session[:status] = status
    session[:word] = word
    session[:label] = label
    session[:sorted_by] = sorted_by

    @tasks = current_user.tasks

    unless status.blank?
      @tasks = @tasks.where(status: status)
    end

    unless word.blank?
      @tasks = @tasks.search(word)
    end

    unless label.blank?
      @tasks = @tasks.joins(:labels).where(labels: {name: label})
    end

    unless sorted_by.blank?
      sort_hash = {"priority" => "desc","deadline" => "asc"}
      @tasks = @tasks.order("#{sorted_by} #{sort_hash[sorted_by]}")
    end

    @tasks
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :judge_login, only: [:edit, :update, :destroy]
  before_action :login_user_reject, only: [:new, :create]
  before_action :set_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to(tasks_path)
    else
      render(:new)
    end
  end


  def edit
  end

  def update
    @user.update(users_params)
    redirect_to tasks_path
  end

  def destroy
    if User.admin.count == 1 && @user.admin?
      return redirect_to tasks_path
    end
    session[:user_id] = nil
    @user.tasks.destroy_all
    @user.destroy
    redirect_to new_session_path
  end

  private
  def set_user
    @user = current_user
  end

  def users_params
    params.require(:user).permit(:name, :password, :email, :user_type)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:user_id]
      if User.find(session[:user_id]).present?
        currenrt_user = User.find(session[:user_id])
      end
    end
  end

  def login?
    session[:user_id].present?
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
  <div>
    <table>
      <tr>
        <td><%= f.label :name, t('.name') %></td>
        <td><%= f.text_field :name  %></td>
      </tr>
      <tr>
        <td><%= f.label :email, t('.email') %></td>
        <td><%= f.text_field :email  %></td>
      </tr>
      <tr>
        <td><%= f.label :password, t('.password') %></td>
        <td><%= f.text_field :password  %></td>
      </tr>
      <tr>
        <td><%= f.label :user_type, t('.user_type') %></td>
        <td><%= f.select :user_type, User.user_types.keys  %></td>
      </tr>
    </table>
  </div>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <%= label_tag :title, t('edit_user'), class: 'title' %>
    <hr />
    <%= form_for @user, url: admin_user_path(@user), method: :put do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
      <%= f.submit 'Register', style: 'font-size: 16px; float: right;' %>
    <% end %>
    <%= button_to 'Back', admin_users_path, method: :get, class: 'btn btn-warning btn-back link-color' %>
  </div>
</div>

app/views/admin/users/index.html.erb
<%
=begin%>

<%= form_tag users_path, method: 'get' ,class: "search" do %>
  <%= select_tag :status, options_for_select(user.statuses, :selected => params[:status]), :include_blank => true %>
  <%= text_field_tag :word, params[:word] %>
  sorted_by:<%= select_tag :sorted_by, options_for_select([["Priority","priority"],["Deadline","deadline"]],:selected => params[:sorted_by]),  :include_blank => true %>
  <%= submit_tag "Search or Sort", class: 'btn btn-info' %>
<% end %>
<%= button_to "Show All", users_path, method: :get %>
<br><br>
<%
=end%>
<table class="table table-striped table-bordered header-table">
  <thead>
    <tr>
      <th>Id</th>
      <th>User Type</th>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Registered At</th>
      <th><%= link_to t('.new_user'), new_admin_user_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td><%= u.id %></td>
        <td><%= u.user_type %></td>
        <td>
          <%= link_to u.name, edit_admin_user_path(u) %>
        </td>
        <td><%= u.email %></td>
        <td><%= u.password %></td>
        <td><%= u.created_at %></td>
        <td class="text-center">
        <%= link_to 'Delete', admin_user_path(id: u), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: 'btn btn-danger btn-new link-color' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>

<%= paginate @users, window: 2, params: {page_click: 1} %>

app/views/admin/users/new.html.erb
<div class="container">
  <div class="row">
    <%= label_tag :title, t('.new_user'), class: 'title' %>
    <hr />
    <%= form_for @user , url: admin_users_path do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
      <%= f.submit 'Register', style: 'font-size: 16px; float: right;' %>
      <% end %>
      <%= button_to 'Back', admin_users_path, method: :get, class: 'btn btn-warning btn-back link-color' %>
    </div>
  </div>

app/views/labels/_form.html.erb
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :label_name %>
  </div>

  <%= f.hidden_field :task_id, value: @task_id %>
  <%= f.hidden_field :user_id, value: current_user.id %>

app/views/labels/edit.html.erb
<div class="container">
  <div class="row">
    <%= label_tag :title, t('.edit_label'), class: 'title' %>
    <hr />
    <%= form_for @label, url: labels_path(@label) do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
      <%= f.submit 'Register', class: 'btn btn-info', style: 'font-size: 16px; float: right;' %>
    <% end %>
    <%= button_to 'Back', tasks_path, method: :get, class: 'btn btn-warning btn-back link-color' %>
    <%= button_to 'Delete', label_path, method: :delete, class: 'btn btn-warning btn-back link-color' %>
  </div>
  <br><br>
  ==Present Labels==<br>
  <% @labels.pluck(:name).uniq.sort.each do |l| %>
    <%= l %><br>
  <% end %>
  ==Present Labels==

</div>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= label.user_id %></td>
        <td><%= label.task_id %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<div class="container">
  <div class="row">
    <%= label_tag :title, t('.new_label'), class: 'title' %>
    <hr />
    <%= form_for @label, url: labels_path do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
      <%= f.submit 'Register', class: 'btn btn-info', style: 'font-size: 16px; float: right;' %>
    <% end %>
    <%= button_to 'Back', tasks_path, method: :get, class: 'btn btn-warning btn-back link-color' %>
  </div>
  <br><br>
  ==Present Labels==<br>
  <% @labels.pluck(:name).uniq.sort.each do |l| %>
    <%= l %><br>
  <% end %>
  ==Present Labels==

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="menu">
        <%= link_to "Personal", tasks_path %>
      </div>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="menu">
        <% if login? %>
        <%= link_to "Edit Profile", edit_user_path(id: current_user.id) %>
          <%= link_to "Sign Out", session_path(id: current_user.id), method: :delete %>
          <%= link_to "Delete Account", user_path(id: current_user.id), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: 'btn btn-danger btn-new link-color' %>
          <% if current_user.admin? %>
            <%= link_to "Admin", admin_users_path %>
          <% end %>
        <% else %>
          <%= link_to "Login", new_session_path %>
          <%= link_to "Sign Up", new_user_path %>
        <% end %>
      </div><br>


    <hr>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
  <div>
    <table>
      <tr>
        <td><%= f.label :title, t('.title') %></td>
        <td><%= f.text_field :title  %></td>
      </tr>
      <tr>
        <td><%= f.label :text, t('.text') %></td>
        <td><%= f.text_area :text  , class: "text-area"%></td>
      </tr>
      <tr>
        <td><%= f.label :status, t('.status') %></td>
        <td><%= f.select :status, Task.statuses.keys%></td>
      </tr>
      <tr>
        <td><%= f.label :priority, t('.priority') %></td>
        <td><%= f.number_field :priority %></td>
      </tr>
      <tr>
        <td><%= f.label :deadline, t('.deadline') %></td>
        <td>
          <%= f.datetime_select :deadline, {}, class: 'form-control' %>
        </td>
      </tr>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </table>
  </div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <%= label_tag :title, t('edit_task'), class: 'title' %>
    <hr />
    <%= form_for @task, url: task_path(@task), method: :put do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
      <%= f.submit 'Register', class: 'btn btn-info', style: 'font-size: 16px; float: right;' %>
    <% end %>
    <%= button_to 'Back', tasks_path, method: :get, class: 'btn btn-warning btn-back link-color' %>
  </div>
</div>

app/views/tasks/index.html.erb
<%= form_tag tasks_path, method: 'get' ,class: "search" do %>

  Status:
      <%= select_tag :status, options_for_select(Task.statuses, :selected => params[:status]), :include_blank => true %>
  Search Word:
      <%= text_field_tag :word, params[:word] %>
  Label:
      <%= select_tag :label, options_for_select(@labels.pluck(:name),:selected => params[:label]),  :include_blank => true %>
  sorted_by:
      <%= select_tag :sorted_by, options_for_select([["Priority","priority"],["Deadline","deadline"]],:selected => params[:sorted_by]),  :include_blank => true %>

  <%= submit_tag "Search or Sort", class: 'btn btn-info' %>
<% end %>
<%= button_to "Show All", tasks_path, method: :get %>


<br><br>
<table class="table table-striped table-bordered header-table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Priority</th>
      <th>Label</th>
      <th></th>
      <th>Title</th>
      <th>Text</th>
      <th>Status</th>
      <th>Created At</th>
      <th>Deadline</th>
      <th><%= link_to t('.new_task'), new_task_path %></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |t| %>
      <tr>
        <td><%= t.id %></td>
        <td><%= t.priority %></td>
        <td>
          <% t.labels.each do |l|  %>
            <%= link_to l.name, edit_label_path(l, task_id: t.id) %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Add Label', new_label_path(task_id: t.id), class: 'btn btn-default' %>
        </td>
        <td>
          <%= link_to t.title, edit_task_path(t) %>
        </td>
        <td><%= t.text %></td>
        <td><%= t.status %></td>
        <td><%= t.created_at %></td>
        <td><%= t.deadline %></td>
        <td class="text-center">
        <%= link_to 'Delete', task_path(id: t), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: 'btn btn-danger btn-new link-color' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>
<div class="pagination">
  <%= paginate @tasks, window: 2, params: {page_click: 1} %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <%= label_tag :title, t('.new_task'), class: 'title' %>
    <hr />
    <%= form_for @task, url: tasks_path do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
      <%= f.submit 'Register', class: 'btn btn-info', style: 'font-size: 16px; float: right;' %>
    <% end %>
    <%= button_to 'Back', tasks_path, method: :get, class: 'btn btn-warning btn-back link-color' %>
  </div>
</div>

app/views/users/_form.html.erb
  <div>
    <table>
      <tr>
        <td><%= f.label :name, t('.name') %></td>
        <td><%= f.text_field :name  %></td>
      </tr>
      <tr>
        <td><%= f.label :email, t('.email') %></td>
        <td><%= f.text_field :email  %></td>
      </tr>
      <tr>
        <td><%= f.label :password, t('.password') %></td>
        <td><%= f.text_field :password  %></td>
      </tr>
    </table>
  </div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
</div>
  <%= form_for @user, url: user_path(@user), method: :put do |f| %>
    <%= render partial: 'form', locals: { f: f } %>
      <%= f.submit 'Register', style: 'font-size: 16px; float: right;' %>
  <% end %>
  </div>

app/views/users/new.html.erb
<h1>Registration</h1>
<%= form_for @user , url: users_path do |f| %>
<div>
  <%= render partial: 'form', locals: { f: f } %>
  <%= f.submit 'Register', style: 'font-size: 16px; float: right;' %>
</div>
<% end %>